INSERT INTO movies (title, year) VALUES ('Побег из Шоушенка', 1994);
INSERT INTO movies (title, year) VALUES ('Крестный отец', 1972);
INSERT INTO movies (title, year) VALUES ('Подозрительные лица', 1995);
INSERT INTO movies (title, year) VALUES ('Звёздные войны: Эпизод V', 1980);
INSERT INTO movies (title, year) VALUES ('Форрест Гамп', 1994);
INSERT INTO movies (title, year) VALUES ('Под покровом ночи', 2007);
INSERT INTO movies (title, year) VALUES ('Список Шиндлера', 1993);
INSERT INTO movies (title, year) VALUES ('Леон', 1994);
INSERT INTO movies (title, year) VALUES ('Властелин колец: Возвращение короля', 2003);
INSERT INTO movies (title, year) VALUES ('Операция «Ы» и другие приключения Шурика', 1965);
INSERT INTO actors (fullname) VALUES ('Тим Роббинс');
INSERT INTO actors (fullname) VALUES ('Морган Фриман');
INSERT INTO actors (fullname) VALUES ('Марлон Брандо');
INSERT INTO actors (fullname) VALUES ('Аль Пачино');
INSERT INTO actors (fullname) VALUES ('Кевин Спейси');
INSERT INTO actors (fullname) VALUES ('Габриэль Бирн');
INSERT INTO actors (fullname) VALUES ('Марк Хэмилл');
INSERT INTO actors (fullname) VALUES ('Харрисон Форд');
INSERT INTO actors (fullname) VALUES ('Том Хэнкс');
INSERT INTO actors (fullname) VALUES ('Робин Райт');
INSERT INTO actors (fullname) VALUES ('Христиан Бэйл');
INSERT INTO actors (fullname) VALUES ('Хит Леджер');
INSERT INTO actors (fullname) VALUES ('Лиам Нисон');
INSERT INTO actors (fullname) VALUES ('Бен Кингсли');
INSERT INTO actors (fullname) VALUES ('Жан Рено');
INSERT INTO actors (fullname) VALUES ('Натали Портман');
INSERT INTO actors (fullname) VALUES ('Иэн МакКеллен');
INSERT INTO actors (fullname) VALUES ('Элайджа Вуд');
INSERT INTO actors (fullname) VALUES ('Александр Демьяненко');
INSERT INTO actors (fullname) VALUES ('Юрий Никулин');
INSERT INTO directors (fullname) VALUES ('Фрэнк Дарабонт');
INSERT INTO directors (fullname) VALUES ('Фрэнсис Форд Коппола');
INSERT INTO directors (fullname) VALUES ('Брайан Сингер');
INSERT INTO directors (fullname) VALUES ('Ирвин Кершнер');
INSERT INTO directors (fullname) VALUES ('Роберт Земекис');
INSERT INTO directors (fullname) VALUES ('Кристофер Нолан');
INSERT INTO directors (fullname) VALUES ('Стивен Спилберг');
INSERT INTO directors (fullname) VALUES ('Люк Бессон');
INSERT INTO directors (fullname) VALUES ('Питер Джексон');
INSERT INTO directors (fullname) VALUES ('Леонид Гайдай');
INSERT INTO directors_movies (director_id, movie_id) VALUES (1, 1);
INSERT INTO directors_movies (director_id, movie_id) VALUES (2, 2);
INSERT INTO directors_movies (director_id, movie_id) VALUES (3, 3);
INSERT INTO directors_movies (director_id, movie_id) VALUES (4, 4);
INSERT INTO directors_movies (director_id, movie_id) VALUES (5, 5);
INSERT INTO directors_movies (director_id, movie_id) VALUES (6, 6);
INSERT INTO directors_movies (director_id, movie_id) VALUES (7, 7);
INSERT INTO directors_movies (director_id, movie_id) VALUES (8, 8);
INSERT INTO directors_movies (director_id, movie_id) VALUES (9, 9);
INSERT INTO directors_movies (director_id, movie_id) VALUES (10, 10);
INSERT INTO actors_movies (actor_id, movie_id) VALUES (1, 1);
INSERT INTO actors_movies (actor_id, movie_id) VALUES (2, 1);
INSERT INTO actors_movies (actor_id, movie_id) VALUES (3, 2);
INSERT INTO actors_movies (actor_id, movie_id) VALUES (4, 2);
INSERT INTO actors_movies (actor_id, movie_id) VALUES (5, 3);
INSERT INTO actors_movies (actor_id, movie_id) VALUES (6, 3);
INSERT INTO actors_movies (actor_id, movie_id) VALUES (7, 4);
INSERT INTO actors_movies (actor_id, movie_id) VALUES (8, 4);
INSERT INTO actors_movies (actor_id, movie_id) VALUES (9, 5);
INSERT INTO actors_movies (actor_id, movie_id) VALUES (10, 5);
INSERT INTO actors_movies (actor_id, movie_id) VALUES (11, 6);
INSERT INTO actors_movies (actor_id, movie_id) VALUES (12, 6);
INSERT INTO actors_movies (actor_id, movie_id) VALUES (13, 7);
INSERT INTO actors_movies (actor_id, movie_id) VALUES (14, 7);
INSERT INTO actors_movies (actor_id, movie_id) VALUES (15, 8);
INSERT INTO actors_movies (actor_id, movie_id) VALUES (16, 8);
INSERT INTO actors_movies (actor_id, movie_id) VALUES (17, 9);
INSERT INTO actors_movies (actor_id, movie_id) VALUES (18, 9);
INSERT INTO actors_movies (actor_id, movie_id) VALUES (19, 10);
INSERT INTO actors_movies (actor_id, movie_id) VALUES (20, 10);

